name: Events Workflow

on: 
    workflow_dispatch: 
    #push: 

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: After checkout
          run: |
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            pwd
            ls -a
          