name: Selenium Test
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  uses: rajkumar-r-org/build-template/.github/workflows/selenium-test.yml@main
  name: Selenium Test
  with:
    website: "https://dotnetappgithubactions.azurewebsites.net/"
    title: "Web App"
    estring: "stopped"
