name: Selenium Scraper
on:
  workflow_dispatch:
    

  
jobs:
  scrape:
    runs-on: windows-latest
    name: Selenium Scraper
        
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install necessary packages
        run: |
          sudo apt update
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Run the scraping script
        id: script
        run: |
          python ./.github/scripts/pytest-firefox.py
        continue-on-error: true
