name: Driver test
on:
  push:
    branches: main

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: Selenium Scraper
    steps:
        - name: Repo checkout
          uses: actions/checkout@v4
          
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        
        - name: Install necessary packages
          run: |
            pip install --upgrade pip
            pip install selenium pytest webdriver-manager
  
        - name: Run the scraping script
          id: script
          run: |
            python ./github/scripts/drivertest.py
          continue-on-error: true
  
