name: Run commands on different operating systems
on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Codes
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip --version
          pip install selenium pytest webdriver-manager
          
